### ISSUE TITLE
which version is tf?

### ISSUE THREAD

**Issue by myboyliu** [jiaqianghuai/tf-lstm-crf-batch#4]
when I am training my model,the error is occured.my tf 's version 1.0.
Building model finished
Traceback (most recent call last):
  File "train.py", line 212, in <module>
    del tf.get_collection_ref('LAYER_NAME_UIDS')[0]
IndexError: list assignment index out of range

**Comment by jiaqianghuai** [comment]
1.0version

发自我的 iPhone
