### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by magic2728** [jiaqianghuai/tf-lstm-crf-batch#5]
I am trying to use your code for experiment, but error appeared:
from utils import iob2, iob_iobes
ImportError: cannot import name iob2
And I checked it that no iob2, iob_iobes exist in the util.py file.
I need your help, thank you.

**Comment by jiaqianghuai** [comment]
thanks for your notice, i have fixed the bug.

**Comment by magic2728** [comment]
thank you for doing that,I will check further.
